sudo: required
language: generic
services:
  - docker
before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t 86tkstar/docker-react-app -f Dockerfile.dev .
script:
  - docker run -e CI=true 86tkstar/docker-react-app npm run test -- --coverage
after_success:
  - echo "Test success"
