name: Deploy Frontend
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - run: docker build -t 86tkstar/react-test -f Dockerfile.dev .
      - run: docker run -e CI=true 86tkstar/react-test npm test -- --coverage

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: getting-stated-app
          environment_name: Getting-stated-app-env
          version_label: ${{ github.sha }}
          existing_bucket_name: elasticbeanstalk-ap-northeast-2-486157951835
          region: ap-northeast-2
          deployment_package: deploy.zip
